title: Joarder Rashid
author: @JoarderRashid
email: your-email@domain.com
description: > EBHS '23
  This is my life during the summer! I was very active and had many expereinces in the summer of 2020!



show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
