title: Joarder Rashid
author: @JoarderRashid
email: your-email@domain.com
description: > EBHS '23
  This is my life during the summer! I was very active and had many expereinces in the summer of 2020!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
